# Generated by Django 5.2.5 on 2025-08-31 11:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_reserved", models.DateField(verbose_name="Дата бронирования")),
                ("time_reserved", models.TimeField(verbose_name="Время бронирования")),
                ("duration", models.PositiveIntegerField(default=3, verbose_name="Продолжительность бронирования")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания")),
                ("message", models.TextField(blank=True, null=True, verbose_name="Сообщение")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.CreateModel(
            name="BookingHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_reserved", models.DateField(verbose_name="Дата бронирования")),
                ("time_reserved", models.TimeField(verbose_name="Время бронирования")),
                ("duration", models.PositiveIntegerField(default=3, verbose_name="Продолжительность бронирования")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания")),
                ("message", models.TextField(blank=True, null=True, verbose_name="Сообщение")),
                ("cancelled_at", models.DateTimeField(verbose_name="Время отмены бронирования")),
            ],
            options={
                "verbose_name": "История бронирования",
                "verbose_name_plural": "История бронирований",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название ресторана")),
                ("address", models.CharField(max_length=255, unique=True, verbose_name="Адрес ресторана")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+7", max_length=128, region=None, unique=True, verbose_name="Номер телефона"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.IntegerField(unique=True, verbose_name="Номер стола")),
                ("seats", models.IntegerField(verbose_name="Количество мест")),
                ("is_booked", models.BooleanField(default=False, verbose_name="Забронирован")),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
            },
        ),
    ]
